### ISSUE TITLE
error when launching

### ISSUE THREAD

**Issue by sudipta1g** [cascadium/wsl-windows-toolbar-launcher#16]
see the error bellow. whats missing?
My installation is OK. I can launch full gnome with VcXsrv

wsl-windows-toolbar
Traceback (most recent call last):
  File "c:\users\sugho\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\sugho\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\sugho\AppData\Local\Programs\Python\Python38\Scripts\wsl-windows-toolbar.exe\__main__.py", line 4, in <module>
  File "c:\users\sugho\appdata\local\programs\python\python38\lib\site-packages\wsl_windows_toolbar\wsl_windows_toolbar.py", line 19, in <module>
    with open("/proc/mounts") as mount_fh:
FileNotFoundError: [Errno 2] No such file or directory: '/proc/mounts'

**Comment by fquinner** [comment]
You need to run it from python within the WSL environment - not on the Windows host - `/proc/mounts` should exist within that environment.
