### ISSUE TITLE
Launching / Installing script in windows environment should not be possible

### ISSUE THREAD

**Issue by Parzival1608vonKatze** [cascadium/wsl-windows-toolbar-launcher#22]
//*libmagic is missing*//

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.1776.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\phmec\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts\wsl-windows-toolbar.exe\__main__.py", line 4, in <module>
  File "C:\Users\phmec\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\wsl_windows_toolbar\wsl_windows_toolbar.py", line 8, in <module>
    import magic
  File "C:\Users\phmec\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\magic.py", line 201, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation

C:\Users\phmec\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts>

**Comment by fquinner** [comment]
The wsl toolbar script should be run from your WSL environment - not from your windows environment.

**Comment by fquinner** [comment]
Some changes in flight to prevent this from happening

**Comment by fquinner** [comment]
Should now only install and run on WSL as of 0.6.0
