### ISSUE TITLE
Jinja2 error when launching wsl-windows-toolbar

### ISSUE THREAD

**Issue by lanouettea** [cascadium/wsl-windows-toolbar-launcher#39]
I followed the instructions in the readme and ended up having an the same issue with raw_input encountered on #37 . 

After applying his fix, I'm getting to the confirmation, then when I press enter, I obtain the following stack:

```
Press <enter> to continue or ctrl+c to abort. [y/N]:
Traceback (most recent call last):
  File "/home/andre/tools/wsl-windows-toolbar-launcher/wsl_windows_toolbar.py", line 546, in <module>
    cli()
  File "/home/andre/tools/wsl-windows-toolbar-launcher/venv/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/andre/tools/wsl-windows-toolbar-launcher/venv/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/andre/tools/wsl-windows-toolbar-launcher/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/andre/tools/wsl-windows-toolbar-launcher/venv/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/andre/tools/wsl-windows-toolbar-launcher/wsl_windows_toolbar.py", line 313, in cli
    env = Environment(loader=PackageLoader('wsl_windows_toolbar', package_path=''))
  File "/home/andre/tools/wsl-windows-toolbar-launcher/venv/lib/python3.9/site-packages/jinja2/loaders.py", line 309, in __init__
    raise ValueError(
ValueError: The 'wsl_windows_toolbar' package was not installed in a way that PackageLoader understands.
```

Any clues?

**Comment by lanouettea** [comment]
Additionnaly, I tried with Python3.8, Python3.9, with the Pypi package or from the latest sources.

**Comment by fquinner** [comment]
Thank you sir
