### ISSUE TITLE
cannot import name 'raw_input' from 'click._compat'

### ISSUE THREAD

**Issue by gwainor** [cascadium/wsl-windows-toolbar-launcher#47]
I am getting this error on a fresh archlinux WSL2 install.

```
Traceback (most recent call last):
  File "/home/goztrk/.local/bin/wsl-windows-toolbar", line 5, in <module>
    from wsl_windows_toolbar.wsl_windows_toolbar import cli
  File "/home/goztrk/.local/lib/python3.10/site-packages/wsl_windows_toolbar/wsl_windows_toolbar.py", line 16, in <module>
    from click._compat import raw_input
ImportError: cannot import name 'raw_input' from 'click._compat' (/home/goztrk/.local/lib/python3.10/site-packages/click/_compat.py)
```

**Comment by gwainor** [comment]
Ohh okay `pip install --user click==7.1.2` did the trick. I don't know why but even if its specified in the `requirements.txt` that it should install click v7.1.2 it installed the latest version.
