### ISSUE TITLE
Can't run 

### ISSUE THREAD

**Issue by Altantsooj** [cascadium/wsl-windows-toolbar-launcher#51]
altantsooj@Altantsooj:~/.local/bin$ wsl-windows-toolbar
Traceback (most recent call last):
  File "/home/altantsooj/.local/bin/wsl-windows-toolbar", line 5, in <module>
    from wsl_windows_toolbar.wsl_windows_toolbar import cli
  File "/home/altantsooj/.local/lib/python3.10/site-packages/wsl_windows_toolbar/wsl_windows_toolbar.py", line 16, in <module>
    from click._compat import raw_input
ImportError: cannot import name 'raw_input' from 'click._compat' (/home/altantsooj/.local/lib/python3.10/site-packages/click/_compat.py)

**Comment by Kalmat** [comment]
Same problem. Can you please explain how did you solve it? Thanks!
